"""
Morning briefing — per-group structured daily summary of yesterday's WhatsApp
ops activity, with weekly/monthly trend context. Surfaces churn signals and
recurring problems and persists the result for the dashboard.

Each group gets its own briefing per day, scheduled at ~06:00 in the group's
local timezone (derived from the group's `country`). The scheduler is expected
to call `run_due_briefings()` hourly; that function picks the groups whose
local time is currently 06:xx and generates their briefing for "yesterday in
group local time" — but only if it doesn't already exist.

A legacy global briefing (no group_id) can still be generated by passing
`group_id=None` to `run_morning_briefing`, useful for ad-hoc back-fills.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

import pytz

from woi_analyzer.claude_client import generate_morning_briefing
from woi_analyzer.config import CONFIG
from woi_analyzer.db import (
    briefing_exists,
    fetch_morning_briefing_input,
    insert_morning_briefing,
    list_active_groups_with_timezones,
)
from woi_analyzer.logging_setup import log

CDMX_TZ = pytz.timezone("America/Mexico_City")
DEFAULT_BRIEFING_HOUR = 6  # 06:xx local time


def _briefing_to_markdown(
    briefing: dict[str, Any],
    date_str: str,
    metrics: dict[str, Any],
    group_name: str | None = None,
) -> str:
    """Render the briefing as markdown for quick rendering / copy-paste."""
    lines: list[str] = []
    title_suffix = f" · {group_name}" if group_name else ""
    lines.append(f"# Morning Briefing · {date_str}{title_suffix}")
    lines.append("")
    if briefing.get("headline"):
        lines.append(f"**{briefing['headline']}**")
        lines.append("")

    lines.append(
        f"**Resumen:** {metrics.get('total_messages', 0)} mensajes · "
        f"{metrics.get('total_incidents', 0)} incidencias "
        f"({metrics.get('incidents_resolved', 0)} resueltas, "
        f"{metrics.get('incidents_escalated', 0)} escaladas) · "
        f"TTFR avg {round((metrics.get('avg_ttfr_seconds') or 0) / 60, 1)}min · "
        f"Sentiment {metrics.get('avg_sentiment')}"
    )
    lines.append("")

    if briefing.get("highlights"):
        lines.append("## Highlights")
        for h in briefing["highlights"]:
            sev = h.get("severity", "info")
            marker = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(sev, "•")
            lines.append(f"- {marker} **{h.get('title', '')}** — {h.get('detail', '')}")
        lines.append("")

    if briefing.get("churn_signals"):
        lines.append("## Señales de churn (atención inmediata)")
        for s in briefing["churn_signals"]:
            grp = s.get("group", "")
            grp_part = f"**{grp}** — " if grp else ""
            lines.append(f"- {grp_part}\"{s.get('quote', '')}\"  ({s.get('context', '')})")
        lines.append("")

    if briefing.get("incidents_summary"):
        lines.append("## Incidencias por categoría")
        for i in briefing["incidents_summary"]:
            trend = i.get("trend", "")
            grp = i.get("group", "")
            grp_part = f"**{grp}** · " if grp else ""
            lines.append(
                f"- {grp_part}{i.get('category', '')} "
                f"· {i.get('count', 0)} ({trend}) — {i.get('note', '')}"
            )
        lines.append("")

    if briefing.get("groups_to_watch"):
        lines.append("## Grupos a vigilar hoy")
        for g in briefing["groups_to_watch"]:
            sev = g.get("severity", "info")
            marker = {"critical": "🔴", "warning": "🟡", "info": "🔵"}.get(sev, "•")
            lines.append(f"- {marker} **{g.get('group', '')}** — {g.get('reason', '')}")
        lines.append("")

    if briefing.get("agents_red_zone"):
        lines.append("## Agentes en zona roja")
        for a in briefing["agents_red_zone"]:
            lines.append(
                f"- **{a.get('agent', '')}** — {a.get('incidents', 0)} incidencias, "
                f"TTFR avg {a.get('ttfr_avg_min', 0)}min"
            )
        lines.append("")

    if briefing.get("trend_note"):
        lines.append("## Tendencia")
        lines.append(briefing["trend_note"])
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def run_morning_briefing(
    target_date: datetime | None = None,
    group_id: int | None = None,
    timezone_name: str | None = None,
) -> dict[str, Any]:
    """
    Generate the morning briefing for `target_date` and `group_id`.

    - `group_id=None` → legacy global briefing.
    - `target_date=None` → yesterday in the local timezone (group's tz, or CDMX).
    - `timezone_name=None` → derived from the group's country, fallback CDMX.
    """
    if timezone_name is None and group_id is not None:
        for g in list_active_groups_with_timezones():
            if int(g["id"]) == int(group_id):
                timezone_name = g["timezone"]
                break

    tz = pytz.timezone(timezone_name) if timezone_name else CDMX_TZ

    if target_date is None:
        target_date = datetime.now(tz) - timedelta(days=1)

    if target_date.tzinfo is None:
        target_date = tz.localize(target_date)
    target_date = target_date.astimezone(tz)

    log.info(
        "morning_briefing_start",
        date=target_date.strftime("%Y-%m-%d"),
        group_id=group_id,
        timezone=str(tz),
    )

    input_data = fetch_morning_briefing_input(
        target_date, group_id=group_id, timezone_name=str(tz)
    )

    try:
        briefing_json, usage = generate_morning_briefing(input_data)
    except Exception as e:
        log.error("morning_briefing_generation_failed", error=str(e), group_id=group_id)
        return {"saved": False, "error": str(e), "group_id": group_id}

    headline = briefing_json.get("headline") or "Briefing diario de operaciones."
    metrics = input_data["yesterday_metrics"]
    group_name = (input_data.get("group") or {}).get("name") if input_data.get("group") else None
    md = _briefing_to_markdown(
        briefing_json, target_date.strftime("%Y-%m-%d"), metrics, group_name=group_name
    )

    try:
        bid = insert_morning_briefing(
            briefing_date=target_date,
            metrics=metrics,
            headline=headline,
            briefing_json=briefing_json,
            briefing_markdown=md,
            claude_model=CONFIG.anthropic.sonnet_model,
            input_tokens=usage.get("input_tokens", 0),
            output_tokens=usage.get("output_tokens", 0),
            group_id=group_id,
            timezone_name=str(tz),
        )

        # Persist Sonnet's churn signals into the dedicated table so they show
        # up across the dashboard (group page, analytics, etc.) — only when
        # this is a per-group briefing.
        churn_persisted = 0
        if group_id is not None:
            try:
                from woi_analyzer.churn_detector import persist_briefing_churn_signals
                churn_persisted = persist_briefing_churn_signals(
                    group_id=group_id, briefing_json=briefing_json
                )
            except Exception as e:
                log.warning("churn_persist_from_briefing_failed", error=str(e), group_id=group_id)

        log.info(
            "morning_briefing_saved",
            id=bid,
            date=target_date.strftime("%Y-%m-%d"),
            group_id=group_id,
            highlights=len(briefing_json.get("highlights", [])),
            churn_signals=len(briefing_json.get("churn_signals", [])),
            churn_persisted=churn_persisted,
            tokens_in=usage.get("input_tokens", 0),
            tokens_out=usage.get("output_tokens", 0),
        )
        return {
            "saved": True,
            "id": bid,
            "date": target_date.strftime("%Y-%m-%d"),
            "group_id": group_id,
            "group_name": group_name,
            "headline": headline,
            "highlights": len(briefing_json.get("highlights", [])),
            "churn_signals": len(briefing_json.get("churn_signals", [])),
            "churn_persisted": churn_persisted,
        }
    except Exception as e:
        log.error("morning_briefing_save_failed", error=str(e), group_id=group_id)
        return {"saved": False, "error": str(e), "group_id": group_id}


def run_due_briefings(
    *, briefing_hour: int = DEFAULT_BRIEFING_HOUR, force: bool = False
) -> list[dict[str, Any]]:
    """
    For every active group, check if it's currently `briefing_hour:xx` in that
    group's local timezone. If yes (and a briefing for "yesterday in that tz"
    doesn't yet exist), generate it.

    Designed to be called once per hour by the scheduler.

    `force=True` ignores the hour gate and the "already exists" check (for
    manual back-fills).
    """
    results: list[dict[str, Any]] = []
    for g in list_active_groups_with_timezones():
        gid = int(g["id"])
        gname = g["name"]
        tz_name = g["timezone"]
        try:
            tz = pytz.timezone(tz_name)
        except Exception:
            log.warning("morning_briefing_tz_unknown", group_id=gid, timezone=tz_name)
            tz = CDMX_TZ
            tz_name = "America/Mexico_City"

        now_local = datetime.now(tz)
        if not force and now_local.hour != briefing_hour:
            continue

        target_date = now_local - timedelta(days=1)

        if not force and briefing_exists(target_date.date(), gid):
            log.debug(
                "morning_briefing_skipped_exists",
                group_id=gid,
                group=gname,
                date=target_date.strftime("%Y-%m-%d"),
            )
            continue

        log.info(
            "morning_briefing_due",
            group_id=gid,
            group=gname,
            timezone=tz_name,
            local_hour=now_local.strftime("%H:%M"),
            target_date=target_date.strftime("%Y-%m-%d"),
        )
        result = run_morning_briefing(
            target_date=target_date, group_id=gid, timezone_name=tz_name
        )
        results.append({"group_id": gid, "group": gname, **result})

    return results
