# Keywords that must match exactly
keywords = [
    "startup",
    "startups",
    "entrepreneur",
    "entrepreneurs",
    "entrepreneurship",
    "innovation",
    "innovative",
    "technology",
    "tech",
    "digital",
    "business",
    "market",
    "investment",
    "investor",
    "funding",
    "venture",
    "capital",
    "ecosystem",
    "accelerator",
    "incubator",
    "scale",
    "scaling",
    "growth",
    "marketplace",
    "platform",
    "product",
    "service",
    "solution",
    "development",
    "research",
    "data",
    "analytics",
    "AI",
    "artificial intelligence",
    "machine learning",
    "blockchain",
    "crypto",
    "fintech",
    "healthtech",
    "edtech",
    "cleantech",
    "sustainability",
    "green",
    "renewable",
    "energy",
    "mobile",
    "app",
    "application",
    "software",
    "hardware",
    "cloud",
    "saas",
    "subscription",
    "revenue",
    "profit",
    "funding round",
    "seed",
    "series a",
    "series b",
    "series c",
    "unicorn",
    "exit",
    "acquisition",
    "merger",
    "partnership",
    "collaboration",
    "network",
    "community",
    "talent",
    "team",
    "leadership",
    "management",
    "strategy",
    "vision",
    "mission",
    "impact",
    "social",
    "environmental",
    "sustainable",
    "renewable",
    "clean",
    "green",
    "circular",
    "recycling",
    "waste",
    "emissions",
    "carbon",
    "climate",
    "biodiversity",
    "conservation",
    "protection",
    "preservation",
    "restoration",
    "regeneration",
    "regenerative",
    "organic",
    "natural",
    "biodegradable",
    "compostable",
    "reusable",
    "recyclable",
    "renewable energy",
    "solar",
    "wind",
    "hydro",
    "geothermal",
    "biomass",
    "biofuel",
    "hydrogen",
    "electric",
    "hybrid",
    "battery",
    "storage",
    "grid",
    "smart",
    "efficiency",
    "optimization",
    "automation",
    "robotics",
    "drones",
    "sensors",
    "IoT",
    "internet of things",
    "connectivity",
    "wireless",
    "5G",
    "6G",
    "satellite",
    "space",
    "aerospace",
    "aviation",
    "transportation",
    "mobility",
    "autonomous",
    "self-driving",
    "electric vehicles",
    "EV",
    "charging",
    "infrastructure",
    "construction",
    "building",
    "architecture",
    "design",
    "engineering",
    "manufacturing",
    "production",
    "supply chain",
    "logistics",
    "distribution",
    "retail",
    "e-commerce",
    "marketplace",
    "platform",
    "marketplace",
    "sharing economy",
    "gig economy",
    "freelance",
    "remote work",
    "work from home",
    "WFH",
    "hybrid work",
    "flexible work",
    "work-life balance",
    "work life balance",
    "work life",
    "personal development",
    "personal improvement",
    "being a leader",
    "curious facts",
    "business facts"
]

# Concepts that can be matched in different forms
concepts = {
    "startup": ["startup", "startups", "start-up", "start-ups", "startup ecosystem", "startup scene", "startup community"],
    "entrepreneur": ["entrepreneur", "entrepreneurs", "entrepreneurship", "founder", "founders", "co-founder", "co-founders"],
    "innovation": ["innovation", "innovative", "innovator", "innovators", "innovating", "breakthrough", "breakthroughs"],
    "technology": ["technology", "tech", "technological", "technologies", "technologist", "technologists"],
    "digital": ["digital", "digitization", "digitalization", "digital transformation", "digitalization"],
    "business": ["business", "businesses", "business model", "business strategy", "business development"],
    "market": ["market", "markets", "marketplace", "market size", "market share", "market leader"],
    "investment": ["investment", "investments", "investor", "investors", "investing", "invested"],
    "funding": ["funding", "fund", "funds", "financing", "financed", "financer", "financers"],
    "venture": ["venture", "ventures", "venture capital", "venture capitalist", "venture capitalists"],
    "capital": ["capital", "capitalization", "capitalize", "capitalized", "capitalizing"],
    "ecosystem": ["ecosystem", "ecosystems", "ecosystem development", "ecosystem builder"],
    "accelerator": ["accelerator", "accelerators", "accelerate", "accelerated", "accelerating"],
    "incubator": ["incubator", "incubators", "incubate", "incubated", "incubating"],
    "scale": ["scale", "scaling", "scaled", "scalable", "scalability"],
    "growth": ["growth", "growing", "grow", "grown", "grows"],
    "product": ["product", "products", "product development", "product market fit"],
    "service": ["service", "services", "service provider", "service delivery"],
    "solution": ["solution", "solutions", "solve", "solved", "solving"],
    "development": ["development", "develop", "developed", "developing", "developer", "developers"],
    "research": ["research", "researcher", "researchers", "researching", "researched"],
    "data": ["data", "dataset", "datasets", "data-driven", "data science", "data scientist"],
    "analytics": ["analytics", "analyst", "analysts", "analyze", "analyzed", "analyzing"],
    "AI": ["AI", "artificial intelligence", "machine learning", "ML", "deep learning", "neural network"],
    "blockchain": ["blockchain", "block chain", "block-chain", "blockchain technology"],
    "crypto": ["crypto", "cryptocurrency", "cryptocurrencies", "crypto market", "crypto trading"],
    "fintech": ["fintech", "financial technology", "fintech startup", "fintech innovation"],
    "healthtech": ["healthtech", "health tech", "health technology", "digital health"],
    "edtech": ["edtech", "education technology", "ed tech", "educational technology"],
    "cleantech": ["cleantech", "clean tech", "clean technology", "green technology"],
    "sustainability": ["sustainability", "sustainable", "sustain", "sustained", "sustaining"],
    "renewable": ["renewable", "renewables", "renewable energy", "renewable resource"],
    "energy": ["energy", "energies", "energy sector", "energy market", "energy transition"],
    "mobile": ["mobile", "mobility", "mobile-first", "mobile app", "mobile development"],
    "app": ["app", "application", "applications", "app development", "app store"],
    "software": ["software", "software development", "software engineer", "software company"],
    "hardware": ["hardware", "hardware development", "hardware company", "hardware startup"],
    "cloud": ["cloud", "cloud computing", "cloud-based", "cloud infrastructure"],
    "saas": ["saas", "software as a service", "SaaS company", "SaaS platform"],
    "subscription": ["subscription", "subscriptions", "subscribe", "subscribed", "subscribing"],
    "revenue": ["revenue", "revenues", "revenue model", "revenue growth"],
    "profit": ["profit", "profits", "profitable", "profitability", "profiting"],
    "funding round": ["funding round", "round of funding", "investment round", "financing round"],
    "seed": ["seed", "seed funding", "seed round", "seed investment"],
    "series a": ["series a", "series A", "series A funding", "series A round"],
    "series b": ["series b", "series B", "series B funding", "series B round"],
    "series c": ["series c", "series C", "series C funding", "series C round"],
    "unicorn": ["unicorn", "unicorns", "unicorn startup", "unicorn company"],
    "exit": ["exit", "exits", "exit strategy", "exit plan"],
    "acquisition": ["acquisition", "acquisitions", "acquire", "acquired", "acquiring"],
    "merger": ["merger", "mergers", "merge", "merged", "merging"],
    "partnership": ["partnership", "partnerships", "partner", "partners", "partnering"],
    "collaboration": ["collaboration", "collaborations", "collaborate", "collaborated", "collaborating"],
    "network": ["network", "networks", "networking", "networked", "networks"],
    "community": ["community", "communities", "community building", "community-driven"],
    "talent": ["talent", "talents", "talent acquisition", "talent pool", "talent management"],
    "team": ["team", "teams", "team building", "team management", "team culture"],
    "leadership": ["leadership", "leader", "leaders", "leading", "led"],
    "management": ["management", "manage", "managed", "managing", "manager", "managers"],
    "strategy": ["strategy", "strategies", "strategic", "strategist", "strategists"],
    "vision": ["vision", "visions", "visionary", "visionaries"],
    "mission": ["mission", "missions", "mission statement", "mission-driven"],
    "impact": ["impact", "impacts", "impactful", "impacting", "impacted"],
    "social": ["social", "social impact", "social enterprise", "social innovation"],
    "environmental": ["environmental", "environment", "environments", "environmentally"],
    "sustainable": ["sustainable", "sustainability", "sustain", "sustained", "sustaining"],
    "renewable": ["renewable", "renewables", "renewable energy", "renewable resource"],
    "clean": ["clean", "clean energy", "clean technology", "clean tech"],
    "green": ["green", "green energy", "green technology", "green tech"],
    "circular": ["circular", "circular economy", "circular business", "circular model"],
    "recycling": ["recycling", "recycle", "recycled", "recyclable", "recyclability"],
    "waste": ["waste", "waste management", "waste reduction", "waste-to-energy"],
    "emissions": ["emissions", "emission", "carbon emissions", "emissions reduction"],
    "carbon": ["carbon", "carbon footprint", "carbon neutral", "carbon reduction"],
    "climate": ["climate", "climate change", "climate action", "climate tech"],
    "biodiversity": ["biodiversity", "biodiverse", "biodiversity conservation"],
    "conservation": ["conservation", "conserve", "conserved", "conserving"],
    "protection": ["protection", "protect", "protected", "protecting"],
    "preservation": ["preservation", "preserve", "preserved", "preserving"],
    "restoration": ["restoration", "restore", "restored", "restoring"],
    "regeneration": ["regeneration", "regenerate", "regenerated", "regenerating"],
    "regenerative": ["regenerative", "regenerative agriculture", "regenerative business"],
    "organic": ["organic", "organically", "organic farming", "organic products"],
    "natural": ["natural", "naturally", "natural resources", "natural products"],
    "biodegradable": ["biodegradable", "biodegradability", "biodegradation"],
    "compostable": ["compostable", "compost", "composting", "composted"],
    "reusable": ["reusable", "reuse", "reused", "reusing"],
    "recyclable": ["recyclable", "recyclability", "recycling"],
    "renewable energy": ["renewable energy", "renewables", "clean energy", "green energy"],
    "solar": ["solar", "solar energy", "solar power", "solar panel", "solar panels"],
    "wind": ["wind", "wind energy", "wind power", "wind turbine", "wind turbines"],
    "hydro": ["hydro", "hydroelectric", "hydropower", "hydro energy"],
    "geothermal": ["geothermal", "geothermal energy", "geothermal power"],
    "biomass": ["biomass", "biomass energy", "biomass power"],
    "biofuel": ["biofuel", "biofuels", "bioenergy", "biomass fuel"],
    "hydrogen": ["hydrogen", "hydrogen energy", "hydrogen fuel", "hydrogen power"],
    "electric": ["electric", "electricity", "electrical", "electrification"],
    "hybrid": ["hybrid", "hybrid vehicle", "hybrid system", "hybrid technology"],
    "battery": ["battery", "batteries", "battery storage", "battery technology"],
    "storage": ["storage", "energy storage", "storage system", "storage technology"],
    "grid": ["grid", "power grid", "smart grid", "grid system"],
    "smart": ["smart", "smart technology", "smart system", "smart solution"],
    "efficiency": ["efficiency", "efficient", "efficiently", "energy efficiency"],
    "optimization": ["optimization", "optimize", "optimized", "optimizing"],
    "automation": ["automation", "automate", "automated", "automating"],
    "robotics": ["robotics", "robot", "robots", "robotic", "robotic system"],
    "drones": ["drones", "drone", "unmanned aerial vehicle", "UAV"],
    "sensors": ["sensors", "sensor", "sensing", "sensor technology"],
    "IoT": ["IoT", "internet of things", "connected devices", "smart devices"],
    "connectivity": ["connectivity", "connected", "connection", "connections"],
    "wireless": ["wireless", "wireless technology", "wireless system"],
    "5G": ["5G", "fifth generation", "5G network", "5G technology"],
    "6G": ["6G", "sixth generation", "6G network", "6G technology"],
    "satellite": ["satellite", "satellites", "satellite technology", "satellite system"],
    "space": ["space", "space technology", "space industry", "space exploration"],
    "aerospace": ["aerospace", "aerospace industry", "aerospace technology"],
    "aviation": ["aviation", "aviation industry", "aviation technology"],
    "transportation": ["transportation", "transport", "transportation system"],
    "mobility": ["mobility", "mobility solution", "mobility service"],
    "autonomous": ["autonomous", "autonomy", "autonomous system"],
    "self-driving": ["self-driving", "self driving", "autonomous driving"],
    "electric vehicles": ["electric vehicles", "EV", "electric vehicle", "EVs"],
    "charging": ["charging", "charge", "charger", "chargers"],
    "infrastructure": ["infrastructure", "infrastructure development", "infrastructure system"],
    "construction": ["construction", "construction industry", "construction technology"],
    "building": ["building", "buildings", "building technology", "building system"],
    "architecture": ["architecture", "architectural", "architect", "architects"],
    "design": ["design", "designer", "designers", "designing", "designed"],
    "engineering": ["engineering", "engineer", "engineers", "engineered"],
    "manufacturing": ["manufacturing", "manufacture", "manufactured", "manufacturer"],
    "production": ["production", "produce", "produced", "producer", "producers"],
    "supply chain": ["supply chain", "supply-chain", "supply chain management"],
    "logistics": ["logistics", "logistic", "logistical", "logistics management"],
    "distribution": ["distribution", "distribute", "distributed", "distributor"],
    "retail": ["retail", "retailer", "retailers", "retailing"],
    "e-commerce": ["e-commerce", "ecommerce", "electronic commerce", "online retail"],
    "marketplace": ["marketplace", "market place", "online marketplace"],
    "sharing economy": ["sharing economy", "share economy", "collaborative consumption"],
    "gig economy": ["gig economy", "gig work", "gig worker", "gig workers"],
    "freelance": ["freelance", "freelancer", "freelancers", "freelancing"],
    "remote work": ["remote work", "remote working", "remote workforce"],
    "work from home": ["work from home", "WFH", "working from home"],
    "hybrid work": ["hybrid work", "hybrid working", "hybrid workplace"],
    "flexible work": ["flexible work", "flexible working", "flexible workplace"],
    "work-life balance": ["work-life balance", "work life balance", "work/life balance", "work/life integration"],
    "personal development": ["personal development", "self-development", "self improvement", "self-improvement", "personal growth"],
    "leadership": ["leadership", "leader", "leaders", "leading", "led", "being a leader", "leadership development"],
    "curious facts": ["curious facts", "interesting facts", "fascinating facts", "amazing facts"],
    "business facts": ["business facts", "business insights", "business knowledge", "business information"]
} 