name: News Monitor Workflow

on:
  schedule:
    - cron: '30 14 * * *'  # Runs at 10:30 AM EST (14:30 UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-news-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Chrome and Chrome WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        chromium-browser --version
        chromedriver --version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager
      
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> .env
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
        echo "EMAIL_RECIPIENT=${{ secrets.EMAIL_RECIPIENT }}" >> .env
        echo "MAKE_WEBHOOK_URL=${{ secrets.MAKE_WEBHOOK_URL }}" >> .env
    
    - name: Run news monitor with debug output
      run: |
        python -c "import os; print('Environment variables:', [k for k in os.environ.keys() if not k.startswith('_')])"
        python -c "import sys; print('Python version:', sys.version)"
        python -c "import selenium; print('Selenium version:', selenium.__version__)"
        echo "Starting news monitor..."
        python main.py
      env:
        PYTHONUNBUFFERED: 1
        DISPLAY: :99
        CHROME_BIN: /usr/bin/chromium-browser
        CHROMEDRIVER_PATH: /usr/bin/chromedriver 